version: '3.9'
services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluserpassword
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
    ports:
      - 3306:3306
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      
#  demo-redisson-lock:
#    image: demo-redisson-lock:0.0.1-SNAPSHOT
#    depends_on:
#      - mysql
#      - redis
#    deploy:
#      replicas: 1
#    restart: always
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo
#      SPRING_DATASOURCE_USERNAME: mysqluser
#      SPRING_DATASOURCE_PASSWORD: mysqluserpassword
#      IMPORT_RANDOM_USER_PARTITIONS: 1
#    ports:
#      - 8080

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - demo-redisson-lock
#    ports:
#      - 9090:9090
